name: Test

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - id: postgres
        uses: ikalnytskyi/action-setup-postgres@v7

      - name: Build
        run: cargo build --release

      - name: Run test
        run: cargo test
        env:
          POSTGRES_CONN_STR_TEST: ${{ steps.postgres.outputs.connection-uri }}
