name: Test

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL
        id: postgres
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
          postgres-version: 17

      - name: Install PostGIS
        run: |
          sudo apt-get install -y postgresql-17-postgis-3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run test
        run: cargo test
        env:
          POSTGRES_CONN_STR_TEST: ${{ steps.postgres.outputs.connection-uri }}
